# Generated by Django 3.0.4 on 2020-04-26 17:18

import apps.cloud.validator
import apps.subject.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=128, verbose_name='title en')),
                ('title_el', models.CharField(max_length=128, verbose_name='title el')),
                ('image', models.ImageField(blank=True, default='images/no_img_available.jpg', max_length=1024, upload_to=apps.subject.models.create_image_path, verbose_name='subject image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='subject description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': "subject's",
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=1024, upload_to=apps.subject.models.create_file_upload_path, validators=[apps.cloud.validator.validate_file_extension], verbose_name='file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='exercise description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject')),
            ],
            options={
                'verbose_name': 'subject_exercise',
                'verbose_name_plural': "subject_exercise's",
                'db_table': 'subject_exercise',
            },
        ),
    ]
